//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.25 at 06:41:45 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://uniovi.com/sdi/soap/ws", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.uniovi.sdi.wsdl;
